### ISSUE TITLE
Are the results of cifar10(resnet18) on msp odin energy and other methods are presented by the Pre-trained Model ResNet18_cifar10 in Pre-trained Models?

### ISSUE THREAD

**Issue by ColdAsYou165** [jhornauer/heatmap_ood#1]
Are the results of cifar10(resnet18) on msp odin energy and other methods are presented by the Pre-trained Model ResNet18_cifar10 in [Pre-trained Models](https://cloudstore.uni-ulm.de/s/Wtpcebb3i4NXDcp)?
I loaded the ResNet18_cifar10 weight from [Pre-trained Models](https://cloudstore.uni-ulm.de/s/Wtpcebb3i4NXDcp), but the results were different from those given in the paper.The results of my testing of ResNet18_cifar10 from [Pre-trained Models](https://cloudstore.uni-ulm.de/s/Wtpcebb3i4NXDcp) are as follows:

![image](https://github.com/jhornauer/heatmap_ood/assets/44527258/b2a8db12-6ab7-4abb-ad5a-f71a213cb210)

**Comment by jhornauer** [comment]
We obtain the results for the different uncertainty estimation models using the pre-trained models provided. To do this, we use the implementations provided in the respective papers and the datasets listed in our paper. 
You must ensure that you use the same test data for your evaluation.
